services:
  api:
    container_name: mcs-backend
    build: ./
    depends_on:
      - postgres
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: lelouch
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres-data: